### ISSUE TITLE
ADJUtil.m initFileURLWithPath error

### ISSUE THREAD

**Issue by picturehit** [adjust/sdks#45] opened 2018-05-02 16:02 UTC
Hello guys 

I saw a new bug on Fabric with adjust sdk, any idea ?

ADJUtil.m line 382
+[ADJUtil writeObject:fileName:objectName:]

Fatal Exception: NSInvalidArgumentException
*** -[NSURL initFileURLWithPath:isDirectory:]: nil string parameter

Thank you

**Comment by uerceg** [comment] 2018-05-02 16:05
Hi @picturehit 

Looks similar to https://github.com/adjust/ios_sdk/issues/320. Is that the issue you're facing? If yes, try updating Adjust SDK to latest version, it should be fixed.

Let us know if you have any other questions.

Cheers

**Comment by picturehit** [comment] 2018-05-03 08:35
Thank you @uerceg I just updated the pod, you can close the ticket, i will reopen it if I see the bug again.
Have a good day !

**Comment by uerceg** [comment] 2018-05-03 08:48
@picturehit 

Sure. 👍 Feel free to reopen it in case the issue is still there.

Good day to you, too. Cheers. 🍺

**Closed by uerceg** 2018-05-03 08:48 UTC
